# -*- coding: utf-8 -*-
"""Student_Management_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jLh_-Rnnq8W20Y8GLn225ytHDixBO9M
"""

students = []

def add_student():
    name = input("Enter name: ")
    roll = input("Enter roll number: ")
    students.append({"name": name, "roll": roll})
    print("Student added successfully!")

def view_students():
    if not students:
        print("No records found.")
    else:
        for s in students:
            print(f"Name: {s['name']}, Roll: {s['roll']}")

def search_student():
    roll = input("Enter roll to search: ")
    for s in students:
        if s['roll'] == roll:
            print("Found:", s)
            return
    print("Student not found.")

def delete_student():
    roll = input("Enter roll to delete: ")
    for s in students:
        if s['roll'] == roll:
            students.remove(s)
            print("Deleted successfully!")
            return
    print("Student not found.")

while True:
    print("\n1. Add\n2. View\n3. Search\n4. Delete\n5. Exit")
    choice = input("Enter choice: ")

    if choice == '1':
        add_student()
    elif choice == '2':
        view_students()
    elif choice == '3':
        search_student()
    elif choice == '4':
        delete_student()
    elif choice == '5':
        break
    else:
        print("Invalid choice")